apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "4"
  creationTimestamp: "2023-06-02T12:58:32Z"
  generation: 4
  labels:
    app: prom
  name: prometheus-1
  namespace: default
  resourceVersion: "159378"
  uid: 617ecc6a-c4ff-4062-8519-ddf89c40bf38
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prom
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prom
    spec:
      containers:
      - image: prom/prometheus
        imagePullPolicy: Always
        name: prometheus
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/prometheus/
          name: test
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: test
        persistentVolumeClaim:
          claimName: cubensquare-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2023-06-02T13:26:19Z"
    lastUpdateTime: "2023-06-02T13:26:19Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-02T15:11:49Z"
    lastUpdateTime: "2023-06-02T15:13:24Z"
    message: ReplicaSet "prom-d46567468" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 4
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 1
