apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom 
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: prom/prometheus 
          name: nginx
