apiVersion: v1
kind: PersistentVolume
metadata:
 name: cubensquare-pv
 labels:
  app: nginx
spec:
  storageClassName: goms
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/harizeus12"
  persistentVolumeReclaimPolicy: Delete
