apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cubensquare-pvc
  labels:
    app: nginx
spec:
  storageClassName: goms
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
